stages:
    - test

variables:
    APPLICATION_NAME: astarte_core

mix:test-coverage:
    stage: test
    image: elixir:1.6.5
    cache:
        key: "$CI_COMMIT_REF_SLUG"
        paths:
            - deps
            - _build
    before_script:
        - mix local.hex --force
        - mix local.rebar
        - mix deps.get
    script:
        - mix coveralls
